POST http://localhost:8000/products HTTP/1.1
Content-Type: "application/json"

{
    "name": "Product test",
    "price": 100.00
}

###

GET http://localhost:8000/products/457e2a30-592e-47a3-9db3-1e4345cfa832 HTTP/1.1
Content-Type: "application/json"

###

GET http://localhost:8000/products HTTP/1.1
Content-Type: "application/json"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc3OTAzMjgsInN1YiI6ImMwY2NkZWVhLWViNWEtNDY4Mi04MjZjLTJiZTUyZTk3Y2I5YyJ9.eosKbYEclVpN5d2u8YEoCibrT1n7Hm5v8l_OBtzBF00

###

PUT http://localhost:8000/products/457e2a30-592e-47a3-9db3-1e4345cfa832a HTTP/1.1
Content-Type: "application/json"

{
    "name": "Product test updated 4",
    "price": 160.00
}

###

DELETE http://localhost:8000/products/62c195ae-dc1b-47a3-b1ad-01d880ede8f9 HTTP/1.1
Content-Type: "application/json"